services:
  h.server:
    # image: ${DOCKER_REGISTRY-}hserver
    image: tda:latest # Tour de app image tag
    container_name: h.server
    build:
      context: .
      dockerfile: src/h.Server/Dockerfile