// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using h.Server.Infrastructure.Database;

#nullable disable

namespace h.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241215164057_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("h.Server.Entities.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("date('now')");

                    b.HasKey("Id");

                    b.ToTable("GamesDbSet");
                });

            modelBuilder.Entity("h.Server.Entities.Games.Game", b =>
                {
                    b.OwnsOne("h.Server.Entities.Games.GameBoard", "Board", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BoardMatrix")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("GameId");

                            b1.ToTable("GamesDbSet");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Board")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
